---
title: "Sus Scrofa - Compare BS vs EMSEQ vs MEGALODON calls"
author: "P_Terzian"
date: "`r Sys.Date()`"
output: html_document
---




```{r, include=FALSE}
library(data.table)
library(Biostrings)
library(ggplot2)
library(DT)
library(reshape2)
```




### LOAD megalodon both runs results
```{r}
## run 1
mega_results_run1 <- fread(file = "/work/project/seqoccin/epigenetique/sus_scrofa/Reference_father/megalodon_calling/sus_scrofa_ref_PAD93746/modified_bases.5mC.bed", stringsAsFactors = FALSE)
colnames(mega_results_run1) <- c("chrm", "start", "stop", "score", "coverage", "strand", "start2", "stop2", "Idonknow", "coverage", "fraction")
hist(mega_results_run1$fraction)
setkey(mega_results_run1, chrm, start)
mega_results_run1 <- mega_results_run1[strand == "+", start := start + 1]
mega_merged1 <- mega_results_run1[, .(coverage = sum(coverage), fraction = sum(fraction) / length(fraction)), by = .(chrm, start)]
setkey(mega_merged1, chrm, start)


## run 2
mega_results_run2 <- fread(file = "/work/project/seqoccin/epigenetique/sus_scrofa/Reference_father/megalodon_calling/sus_scrofa_ref_PAE20806/modified_bases.5mC.bed", stringsAsFactors = FALSE)
colnames(mega_results_run2) <- c("chrm", "start", "stop", "score", "coverage", "strand", "start2", "stop2", "Idonknow", "coverage", "fraction")
setkey(mega_results_run2, chrm, start)
mega_results_run2 <- mega_results_run2[strand == "+", start := start + 1]
mega_merged2 <- mega_results_run2[, .(coverage = sum(coverage), fraction = sum(fraction) / length(fraction)), by = .(chrm, start)]
setkey(mega_merged2, chrm, start)


## merge both runs
megapooled <- rbind(mega_merged1, mega_merged2)
setkey(megapooled, chrm, start)
megapooled <- megapooled[, .(coverage = sum(coverage), fraction = sum(fraction) / length(fraction)), by = .(chrm, start)]

## filter coverage
megapooled <- megapooled[coverage < 100 & coverage > 5]

nrow(megapooled)

rm(list = c("mega_results_run1", "mega_merged1", "mega_results_run2", "mega_merged2"))

```



### Load bismark cytosine_report POOLED
```{r}

## Path to folder containing stranded cpg reports from nfcore/methylseq
pathToFiles = "/work2/project/seqoccin/epigenetique/CelineV/Project_A2P1b-PlaGe-Porc.1470/Pool_run_bisulfite_porc_ref/MethylSeq-nfcore/Sscrofa_per-lane_param-zymo/results/bismark_methylation_calls/stranded_CpG_report/"

## list file
list_files <- list.files(path = pathToFiles)


## run through the list and read file
study_DT <- lapply(1:length(list_files), function(x){
    
    
  
    bedcoverageFile           <- fread(file = paste(pathToFiles, list_files[x], sep=""))
    colnames(bedcoverageFile) <- c("chrm", "start", "strand", "Cyt", "Thy", "di_context", "tri_context")
    
    return(bedcoverageFile)
    
})

## bind all DT in list
study_DT    <- do.call(rbind, study_DT)

## prepare for strand merging
study_DT <- study_DT[strand == "-", start := start - 1]

## Merge counts
merged_study_DT <- study_DT[, .(Cyt = sum(Cyt), Thy = sum(Thy)), by = .(chrm, start)]

## remove uncovered genomic positions
merged_study_DT <- merged_study_DT[Cyt != 0 | Thy != 0]

## compute fraction and coverage per genomic positions
merged_study_DT[, fraction := Cyt / (Cyt + Thy)]
merged_study_DT[, cov := Cyt + Thy ]

## filter low covered positions and outlayers
merged_study_DT <- merged_study_DT[cov < 100 & cov >5]

##check depth of coverage :
mean(merged_study_DT$cov)

rm(study_DT)
rm(merged_study_DT_stranded)
gc()

nrow(merged_study_DT)

```



### Load EM-Seq results
```{r}
#Load bismark cytosine_report

pathToFiles = "/work/project/seqoccin/epigenetique/CelineV/Project_A2P1b-PlaGe-Porc.1470/Run_Emseq_porc_ref.18919/MethylSeq-nfcore/Sus_scrofa_param-em-seq/results/bismark_methylation_calls/stranded_CpG_report/"

list_files <- list.files(path = pathToFiles)

study_DT <- lapply(1:length(list_files), function(x){
    
    
  
    bedcoverageFile           <- fread(file = paste(pathToFiles, list_files[x], sep=""))
    colnames(bedcoverageFile) <- c("chrm", "start", "strand", "Cyt", "Thy", "di_context", "tri_context")
    
    return(bedcoverageFile)
    
  })

study_DT    <- do.call(rbind, study_DT)

study_DT <- study_DT[strand == "-", start := start - 1]

merged_study_DT_EMSEQ <- study_DT[, .(Cyt = sum(Cyt), Thy = sum(Thy)), by = .(chrm, start)]

merged_study_DT_EMSEQ <- merged_study_DT_EMSEQ[Cyt != 0 | Thy != 0]

merged_study_DT_EMSEQ[, fraction := Cyt / (Cyt + Thy)]
merged_study_DT_EMSEQ[, cov := Cyt + Thy ]

rm(study_DT)
gc()

##check depth of coverage :
mean(merged_study_DT_EMSEQ$cov)

merged_study_DT_EMSEQ <- merged_study_DT_EMSEQ[cov < 100 & cov > 5]

hist(merged_study_DT_EMSEQ$fraction)

setkey(merged_study_DT_EMSEQ, chrm, start)

nrow(merged_study_DT_EMSEQ)

```




### Compare megalodon run with BS and Emseq
```{r}

#Megapooled vs BSpooled
setkey(megapooled, chrm, start)
setkey(merged_study_DT, chrm, start)
setkey(merged_study_DT_EMSEQ, chrm, start)

nrow(megapooled)
nrow(merged_study_DT)
nrow(merged_study_DT_EMSEQ)

megapooledvBSpooled <- megapooled[merged_study_DT, nomatch=0]
nrow(megapooledvBSpooled)
cormegapooledvBSpooled <- cor(megapooledvBSpooled$fraction, megapooledvBSpooled$i.fraction)


megapooledvEMseqpooled <- megapooled[merged_study_DT_EMSEQ, nomatch=0]
cormegapooledvEMseqpooled <- cor(megapooledvEMseqpooled$fraction, megapooledvEMseqpooled$i.fraction)

rm(mega1vEMseqpooled)
rm(mega2vBSpooled)
rm(megapooledvEMseqpooled)
gc()

```


### Compare WGBS pooled with Emseq
```{r}
EmseqvBSpooled     <- merged_study_DT_EMSEQ[merged_study_DT, nomatch=0]
nrow(EmseqvBSpooled)
corEmseqvBSpooled<- cor(EmseqvBSpooled$fraction, EmseqvBSpooled$i.fraction)

colpooledwgbs <- c(1, corEmseqvBSpooled, cormegapooledvBSpooled)
colemseq    <- c(  corEmseqvBSpooled, 1, cormegapooledvEMseqpooled)
colmegapooled <- c( cormegapooledvBSpooled, cormegapooledvEMseqpooled,  1)

correlation_matrix <- data.frame(pooledWgbs = colpooledwgbs, Emseq = colemseq, pooledONT = colmegapooled)
rownames(correlation_matrix) <- c("pooledwgbs", "emseq","pooledONT")

fwrite(x = round(correlation_matrix, 2), file = "scrofa_Correlation_matrix_heatmaptechdatapaper_wholeCpG.tsv", sep = "\t")

```



