---
title: "Seqoccin's tech correlation Coturnix"
author: "P_Terzian"
date: "`r Sys.Date()`"
output: html_document
highlight: github
---


```{r, include=FALSE}
library(data.table)
library(Biostrings)
library(ggplot2)
library(DT)
library(reshape2)

```



# LOAD Pacbio run1 & 2 result
```{r}
primrose_results_run1 <- fread(file = "/work/project/seqoccin/epigenetique/coturnix_japonica/PacBio/reference_coturnix/analysis/run_200820_203625/m64122_200820_203625.ccs.bedmethyl", stringsAsFactors = FALSE)
colnames(primrose_results_run1) <- c("chrm", "start", "stop", "name", "score", "strand", "start2", "stop2", "Idonknow", "count", "fraction", "cannonical", "modified", "filtered")
hist(primrose_results_run1$fraction)
setkey(primrose_results_run1, chrm, start)
primrose_results_run1 <- primrose_results_run1[strand == "+", start := start + 1]
primrose_merged1 <- primrose_results_run1[, .(count = sum(count), fraction = sum(fraction) / length(fraction)), by = .(chrm, start)]
setkey(primrose_merged1, chrm, start)

primrose_results_run2 <- fread(file = "/work/project/seqoccin/epigenetique/coturnix_japonica/PacBio/reference_coturnix/analysis/run_201001_030231/m64122_201001_030231.ccs.bedmethyl", stringsAsFactors = FALSE)
colnames(primrose_results_run2) <- c("chrm", "start", "stop", "name", "score", "strand", "start2", "stop2", "Idonknow", "count", "fraction", "cannonical", "modified", "filtered")
hist(primrose_results_run2$fraction)
setkey(primrose_results_run2, chrm, start)
primrose_results_run2 <- primrose_results_run2[strand == "+", start := start + 1]
primrose_merged2 <- primrose_results_run2[, .(count = sum(count), fraction = sum(fraction) / length(fraction)), by = .(chrm, start)]
setkey(primrose_merged2, chrm, start)

primrose_merged <- rbind(primrose_merged1, primrose_merged2)
primrose_merged <- primrose_merged[, .(count = sum(count), fraction = sum(fraction) / length(fraction)), by = .(chrm, start)]

primrose_merged <- primrose_merged[count < 100 & count > 5]
setkey(primrose_merged, chrm, start)

nrow(primrose_merged)


rm(list = c("primrose_results_run1", "primrose_merged1", "primrose_results_run2", "primrose_merged2"))


```



# LOAD megalodon both runs results
```{r}
mega_results_run1 <- fread(file = "/work/project/seqoccin/epigenetique/coturnix_japonica/PromethION_PAE47187_Promethion_PAE47965_natifs/megalodon_calling/2022_last_calls_with_bam_fastq_mod/coturnix_ref_PAE47187/modified_bases.5mC.bed", stringsAsFactors = FALSE)
colnames(mega_results_run1) <- c("chrm", "start", "stop", "score", "count", "strand", "start2", "stop2", "Idonknow", "count2", "fraction")
# hist(mega_results_run1$fraction)
setkey(mega_results_run1, chrm, start)
mega_results_run1 <- mega_results_run1[strand == "+", start := start + 1]
mega_merged1 <- mega_results_run1[, .(count = sum(count), fraction = sum(fraction) / length(fraction)), by = .(chrm, start)]
setkey(mega_merged1, chrm, start)


mega_results_run2 <- fread(file = "/work/project/seqoccin/epigenetique/coturnix_japonica/PromethION_PAE47187_Promethion_PAE47965_natifs/megalodon_calling/2022_last_calls_with_bam_fastq_mod/coturnix_ref_PAE47965/modified_bases.5mC.bed", stringsAsFactors = FALSE)
colnames(mega_results_run2) <- c("chrm", "start", "stop", "score", "count", "strand", "start2", "stop2", "Idonknow", "count2", "fraction")
setkey(mega_results_run2, chrm, start)
mega_results_run2 <- mega_results_run2[strand == "+", start := start + 1]
mega_merged2 <- mega_results_run2[, .(count = sum(count), fraction = sum(fraction) / length(fraction)), by = .(chrm, start)]
setkey(mega_merged2, chrm, start)


megapooled <- rbind(mega_merged1, mega_merged2)
setkey(megapooled, chrm, start)
megapooled <- megapooled[, .(coverage = sum(count), fraction = sum(fraction) / length(fraction)), by = .(chrm, start)]

megapooled <- megapooled[coverage < 100 & coverage > 5]

rm(list = c("mega_results_run1", "mega_merged1", "mega_merged2", "mega_results_run2"))

nrow(megapooled)

```


## Load bismark cytosine_report POOLED
```{r}
pathToFiles = "/work/project/seqoccin/epigenetique/CelineV/Project_A2P1a-PlaGe-Caille.1447/Pool_run_bisulfite/MethylSeq-nfcore/coturnix_per-lane_param-zymo/results/bismark_methylation_calls/stranded_CpG_report/"

list_files <- list.files(path = pathToFiles)

study_DT <- lapply(1:length(list_files), function(x){
    
    
  
    bedcoverageFile           <- fread(file = paste(pathToFiles, list_files[x], sep=""))
    colnames(bedcoverageFile) <- c("chrm", "start", "strand", "Cyt", "Thy", "di_context", "tri_context")
    
    return(bedcoverageFile)
    
  })

study_DT    <- do.call(rbind, study_DT)

study_DT <- study_DT[strand == "-", start := start - 1]

merged_study_DT <- study_DT[, .(Cyt = sum(Cyt), Thy = sum(Thy)), by = .(chrm, start)]

merged_study_DT <- merged_study_DT[Cyt != 0 | Thy != 0]

merged_study_DT[, fraction := Cyt / (Cyt + Thy)]
merged_study_DT[, cov := Cyt + Thy ]

merged_study_DT <- merged_study_DT[cov >  5 & cov < 100]

nrow(merged_study_DT)

rm(study_DT)
gc()

```


### Load EM-Seq results
```{r}
#Load bismark cytosine_report

pathToFiles = "/work/project/seqoccin/epigenetique/CelineV/Project_A2P1a-PlaGe-Caille.1447/Run_Emseq_caille_ref.18827/MethylSeq-nfcore/Coturnix_japonica_other-param/results/bismark_methylation_calls/stranded_CpG_report/"

list_files <- list.files(path = pathToFiles)

study_DT <- lapply(1:length(list_files), function(x){
    
    
  
    bedcoverageFile           <- fread(file = paste(pathToFiles, list_files[x], sep=""))
    colnames(bedcoverageFile) <- c("chrm", "start", "strand", "Cyt", "Thy", "di_context", "tri_context")
    
    return(bedcoverageFile)
    
  })

study_DT    <- do.call(rbind, study_DT)

study_DT <- study_DT[strand == "-", start := start - 1]


merged_study_DT_EMSEQ <- study_DT[, .(Cyt = sum(Cyt), Thy = sum(Thy)), by = .(chrm, start)]

merged_study_DT_EMSEQ <- merged_study_DT_EMSEQ[Cyt != 0 | Thy != 0]


merged_study_DT_EMSEQ[, fraction := Cyt / (Cyt + Thy)]
merged_study_DT_EMSEQ[, cov := Cyt + Thy ]


rm(study_DT)
gc()


##check depth of coverage :
mean(merged_study_DT_EMSEQ$cov)

merged_study_DT_EMSEQ <- merged_study_DT_EMSEQ[cov >  5 & cov < 100]
setkey(merged_study_DT_EMSEQ, chrm, start)

nrow(merged_study_DT_EMSEQ)

```


### Compare megalodon run with themself and BS and Emseq
```{r}
#Megapooled vs BSpooled
megapooledvBSpooled <- megapooled[merged_study_DT, nomatch=0]
nrow(megapooledvBSpooled)
cormegapooledvBSpooled <- cor(megapooledvBSpooled$fraction, megapooledvBSpooled$i.fraction)


megapooledvEMseqpooled <- megapooled[merged_study_DT_EMSEQ, nomatch=0]
cormegapooledvEMseqpooled <- cor(megapooledvEMseqpooled$fraction, megapooledvEMseqpooled$i.fraction)

rm(mega1vEMseqpooled)
rm(mega2vBSpooled)
rm(megapooledvEMseqpooled)
gc()

```

### Compare WGBS single runs with themself and ONT and Emseq
```{r}
#primrose_mergedpool
primrose_mergedvmegapooled            <- primrose_merged[megapooled, nomatch=0]
nrow(primrose_mergedvmegapooled)
primrose_mergedvEmseq               <- primrose_merged[merged_study_DT_EMSEQ, nomatch=0]
nrow(primrose_mergedvEmseq)
primrose_mergedvBSpooled              <- primrose_merged[merged_study_DT, nomatch=0]
nrow(primrose_mergedvBSpooled)
  
corprimrose_mergedvmegapooled          <- cor(primrose_mergedvmegapooled$fraction, primrose_mergedvmegapooled$i.fraction)  
corprimrose_mergedvEmseq             <- cor(primrose_mergedvEmseq$fraction, primrose_mergedvEmseq$i.fraction)  
corprimrose_mergedvBSpooled            <- cor(primrose_mergedvBSpooled$fraction, primrose_mergedvBSpooled$i.fraction)  
```

### Compare WGBS pooled with Emseq
```{r}
EmseqvBSpooled     <- merged_study_DT_EMSEQ[merged_study_DT, nomatch=0]
nrow(EmseqvBSpooled)
corEmseqvBSpooled<- cor(EmseqvBSpooled$fraction, EmseqvBSpooled$i.fraction)

colpooledwgbs <- c(1, corEmseqvBSpooled, cormegapooledvBSpooled,corprimrose_mergedvBSpooled)
colemseq    <- c(  corEmseqvBSpooled, 1, cormegapooledvEMseqpooled, corprimrose_mergedvEmseq)
colmegapooled <- c( cormegapooledvBSpooled, cormegapooledvEMseqpooled,  1,  corprimrose_mergedvmegapooled)
colpacbiopooled <- c( corprimrose_mergedvBSpooled, corprimrose_mergedvEmseq, corprimrose_mergedvmegapooled,  1)

correlation_matrix <- data.frame(pooledWgbs = colpooledwgbs, Emseq = colemseq, pooledONT = colmegapooled, hifipooled = colpacbiopooled)
rownames(correlation_matrix) <- c("pooledwgbs", "emseq","pooledONT", "hifipooled")

fwrite(x = round(correlation_matrix, 2), file = "Correlation_matrix_heatmaptechdatapaper_nofilter_5X.tsv", sep = "\t")

```


