---
title: "Seqoccin's reproducibility Coturnix"
author: "P_Terzian"
date: "`r Sys.Date()`"
output: html_document
highlight: github
---


```{r, include=FALSE}
library(data.table)
library(Biostrings)
library(ggplot2)
library(DT)
library(reshape2)

```



# LOAD Pacbio run1 & 2 result
```{r}
primrose_results_run1 <- fread(file = "/data/home/terzianps/seqoccin/quail/Pacbio_method/Seqoccin.Quail.PacBio.030231.ccs.bedmethyl", stringsAsFactors = FALSE)
colnames(primrose_results_run1) <- c("chrm", "start", "stop", "name", "score", "strand", "start2", "stop2", "Idonknow", "count", "fraction", "cannonical", "modified", "filtered")
hist(primrose_results_run1$fraction)
setkey(primrose_results_run1, chrm, start)
primrose_results_run1 <- primrose_results_run1[strand == "+", start := start + 1]
primrose_merged1 <- primrose_results_run1[, .(count = sum(count), fraction = sum(fraction) / length(fraction)), by = .(chrm, start)]
setkey(primrose_merged1, chrm, start)
primrose_merged1 <- primrose_merged1[count < 100 & count > 5]

primrose_results_run2 <- fread(file = "/data/home/terzianps/seqoccin/quail/Pacbio_method/Seqoccin.Quail.PacBio.203625.ccs.bedmethyl", stringsAsFactors = FALSE)
colnames(primrose_results_run2) <- c("chrm", "start", "stop", "name", "score", "strand", "start2", "stop2", "Idonknow", "count", "fraction", "cannonical", "modified", "filtered")
hist(primrose_results_run2$fraction)
setkey(primrose_results_run2, chrm, start)
primrose_results_run2 <- primrose_results_run2[strand == "+", start := start + 1]
primrose_merged2 <- primrose_results_run2[, .(count = sum(count), fraction = sum(fraction) / length(fraction)), by = .(chrm, start)]
setkey(primrose_merged2, chrm, start)
primrose_merged2 <- primrose_merged2[count < 100 & count > 5]


nrow(primrose_merged1)
nrow(primrose_merged2)

rm(list = c("primrose_results_run1", "primrose_results_run2"))
```



# LOAD megalodon both runs results
```{r}
mega_results_run1 <- fread(file = "/data/home/terzianps/seqoccin/quail/ONT_method/Seqoccin.Quail.ONT.PAE47187.modified_bases.5mC.bed", stringsAsFactors = FALSE)
colnames(mega_results_run1) <- c("chrm", "start", "stop", "score", "coverage", "strand", "start2", "stop2", "Idonknow", "coverage", "fraction")
hist(mega_results_run1$fraction)
setkey(mega_results_run1, chrm, start)
mega_results_run1 <- mega_results_run1[strand == "+", start := start + 1]
mega_merged1 <- mega_results_run1[, .(coverage = sum(coverage), fraction = sum(fraction) / length(fraction)), by = .(chrm, start)]
setkey(mega_merged1, chrm, start)
mega_merged1 <- mega_merged1[coverage < 100 & coverage > 5]

mega_results_run2 <- fread(file = "/data/home/terzianps/seqoccin/quail/ONT_method/Seqoccin.Quail.ONT.PAE47965.modified_bases.5mC.bed", stringsAsFactors = FALSE)
colnames(mega_results_run2) <- c("chrm", "start", "stop", "score", "coverage", "strand", "start2", "stop2", "Idonknow", "coverage", "fraction")
setkey(mega_results_run2, chrm, start)
mega_results_run2 <- mega_results_run2[strand == "+", start := start + 1]
mega_merged2 <- mega_results_run2[, .(coverage = sum(coverage), fraction = sum(fraction) / length(fraction)), by = .(chrm, start)]
setkey(mega_merged2, chrm, start)
mega_merged2 <- mega_merged2[coverage < 100 & coverage > 5]

rm(list = c("mega_results_run1", "mega_results_run2"))
gc()
print("this works 1")

nrow(mega_merged1)
nrow(mega_merged2)

```


## Load bismark cytosine_report
```{r}
# Load bismark cytosine_report

pathToFiles = "/data/home/terzianps/seqoccin/quail/WGBS_method/"

list_files <- list.files(path = pathToFiles)

wgbsfiletype <- c('wgbs3', 'wgbs1', 'wgbs2', 'wgbs3', 'wgbs1', 'wgbs2')

study_DT <- lapply(1:length(list_files), function(x){
    
    bedcoverageFile           <- fread(file = paste(pathToFiles, list_files[x], sep=""))
    colnames(bedcoverageFile) <- c("chrm", "start", "strand", "Cyt", "Thy", "di_context", "tri_context")
    bedcoverageFile$type <- wgbsfiletype[x]
    return(bedcoverageFile)
  })

study_DT    <- do.call(rbind, study_DT)


study_DT <- study_DT[strand == "-", start := start - 1]

merged_study_DT_typed <- study_DT[, .(Cyt = sum(Cyt), Thy = sum(Thy)), by = .(chrm, start, type)]

merged_study_DT_typed <- merged_study_DT_typed[Cyt != 0 | Thy != 0]

merged_study_DT_typed[, fraction := Cyt / (Cyt + Thy)]
merged_study_DT_typed[, cov := Cyt + Thy ]

rm(study_DT)
gc()

wgbs1 <- merged_study_DT_typed[cov > 5 & cov < 100 & type == "wgbs1"][]
wgbs2 <- merged_study_DT_typed[cov > 5 & cov < 100 & type == "wgbs2"][]
wgbs3 <- merged_study_DT_typed[cov > 5 & cov < 100 & type == "wgbs3"][]

nrow(wgbs1)
nrow(wgbs2)
nrow(wgbs3)

setkey(wgbs1, chrm, start)
setkey(wgbs2, chrm, start)
setkey(wgbs3, chrm, start)


rm(merged_study_DT_typed)
gc()

```


### Load EM-Seq results
```{r}
#Load bismark cytosine_report

pathToFiles = "/data/home/terzianps/seqoccin/quail/EM-Seq_method/"

list_files <- list.files(path = pathToFiles)

study_DT <- lapply(1:length(list_files), function(x){
    
    
  
    bedcoverageFile           <- fread(file = paste(pathToFiles, list_files[x], sep=""))
    colnames(bedcoverageFile) <- c("chrm", "start", "strand", "Cyt", "Thy", "di_context", "tri_context")
    
    return(bedcoverageFile)
    
})

study_DT    <- do.call(rbind, study_DT)


study_DT <- study_DT[strand == "-", start := start - 1]

merged_study_DT_EMSEQ <- study_DT[, .(Cyt = sum(Cyt), Thy = sum(Thy)), by = .(chrm, start)]

merged_study_DT_EMSEQ <- merged_study_DT_EMSEQ[Cyt != 0 | Thy != 0]


merged_study_DT_EMSEQ[, fraction := Cyt / (Cyt + Thy)]
merged_study_DT_EMSEQ[, cov := Cyt + Thy ]


rm(study_DT)
gc()


##check depth of coverage :
mean(merged_study_DT_EMSEQ$cov)

merged_study_DT_EMSEQ <- merged_study_DT_EMSEQ[cov >  5 & cov < 100]

setkey(merged_study_DT_EMSEQ, chrm, start)

nrow(merged_study_DT_EMSEQ)

```


### Compare megalodon run with themself and BS and Emseq
```{r}
#Megapooled vs BSpooled
#Mega1 vs Mega2
mega1vmega2 <- mega_merged1[mega_merged2, nomatch=0]
cormega1vmega2 <- cor(mega1vmega2$fraction, mega1vmega2$i.fraction)
rm(mega1vmega2)


rm(mega1vEMseqpooled)
gc()

```

```{r}
####
#Mega1 vs EMseqpull
mega1vEMseqpull <- mega_merged1[merged_study_DT_EMSEQ, nomatch=0]
cormega1vEMseqpull <- cor(mega1vEMseqpull$fraction, mega1vEMseqpull$i.fraction)
#Mega2 vs EMseqpull
mega2vEMSEQ <- mega_merged2[merged_study_DT_EMSEQ, nomatch=0]
cormega2vEMseqpull <- cor(mega2vEMSEQ$fraction, mega2vEMSEQ$i.fraction)

```

```{r}
##wgbs1
wgbs1vwgbs2     <- wgbs1[wgbs2, nomatch=0]
wgbs1vwgbs3     <- wgbs1[wgbs3, nomatch=0]
wgbs1vmega1     <- wgbs1[mega_merged1, nomatch=0]
wgbs1vmega2     <- wgbs1[mega_merged2, nomatch=0]
wgbs1vEmseq     <- wgbs1[merged_study_DT_EMSEQ, nomatch=0]


##wgbs2
wgbs2vwgbs3     <- wgbs2[wgbs3, nomatch=0]
wgbs2vmega1     <- wgbs2[mega_merged1, nomatch=0]
wgbs2vmega2     <- wgbs2[mega_merged2, nomatch=0]
wgbs2vEmseq     <- wgbs2[merged_study_DT_EMSEQ, nomatch=0]

##wgbs3
wgbs3vmega1     <- wgbs3[mega_merged1, nomatch=0]
wgbs3vmega2     <- wgbs3[mega_merged2, nomatch=0]
wgbs3vEmseq     <- wgbs3[merged_study_DT_EMSEQ, nomatch=0]


corwgbs1vwgbs2    <- cor(wgbs1vwgbs2$fraction, wgbs1vwgbs2$i.fraction)
corwgbs1vwgbs3    <- cor(wgbs1vwgbs3$fraction, wgbs1vwgbs3$i.fraction)
corwgbs2vwgbs3    <- cor(wgbs2vwgbs3$fraction, wgbs2vwgbs3$i.fraction)
corwgbs1vmega1    <- cor(wgbs1vmega1$fraction, wgbs1vmega1$i.fraction)
corwgbs1vmega2    <- cor(wgbs1vmega2$fraction, wgbs1vmega2$i.fraction)
corwgbs1vEmseq    <- cor(wgbs1vEmseq$fraction, wgbs1vEmseq$i.fraction)
corwgbs2vmega1    <- cor(wgbs2vmega1$fraction, wgbs2vmega1$i.fraction)
corwgbs2vmega2    <- cor(wgbs2vmega2$fraction, wgbs2vmega2$i.fraction)
corwgbs2vEmseq    <- cor(wgbs2vEmseq$fraction, wgbs2vEmseq$i.fraction)
corwgbs3vmega1    <- cor(wgbs3vmega1$fraction, wgbs3vmega1$i.fraction)
corwgbs3vmega2    <- cor(wgbs3vmega2$fraction, wgbs3vmega2$i.fraction)
corwgbs3vEmseq    <- cor(wgbs3vEmseq$fraction, wgbs3vEmseq$i.fraction)
```


```{r}
#primrose_merged1
primrose_merged1vprimrose_merged2   <-  primrose_merged1[primrose_merged2, nomatch=0]
primrose_merged1vwgbs1              <-  primrose_merged1[wgbs1, nomatch=0]
primrose_merged1vwgbs2              <-  primrose_merged1[wgbs2, nomatch=0]
primrose_merged1vwgbs3              <-  primrose_merged1[wgbs3, nomatch=0]
primrose_merged1vmega1              <-  primrose_merged1[mega_merged1, nomatch=0]
primrose_merged1vmega2              <-  primrose_merged1[mega_merged2, nomatch=0]
primrose_merged1vEmseq              <-  primrose_merged1[merged_study_DT_EMSEQ, nomatch=0]


#primrose_merged2          
primrose_merged2vwgbs1              <- primrose_merged2[wgbs1  , nomatch=0] 
primrose_merged2vwgbs2              <- primrose_merged2[wgbs2, nomatch=0]
primrose_merged2vwgbs3              <- primrose_merged2[wgbs3, nomatch=0]
primrose_merged2vmega1              <- primrose_merged2[mega_merged1, nomatch=0]
primrose_merged2vmega2              <- primrose_merged2[mega_merged2, nomatch=0]
primrose_merged2vEmseq              <- primrose_merged2[merged_study_DT_EMSEQ, nomatch=0]


#primrose_merged1
corprimrose_merged1vprimrose_merged2 <- cor(primrose_merged1vprimrose_merged2$fraction, primrose_merged1vprimrose_merged2$i.fraction)   
corprimrose_merged1vwgbs1            <- cor(primrose_merged1vwgbs1$fraction, primrose_merged1vwgbs1$i.fraction)  
corprimrose_merged1vwgbs2            <- cor(primrose_merged1vwgbs2$fraction, primrose_merged1vwgbs2$i.fraction)  
corprimrose_merged1vwgbs3            <- cor(primrose_merged1vwgbs3$fraction, primrose_merged1vwgbs3$i.fraction)  
corprimrose_merged1vmega1            <- cor(primrose_merged1vmega1$fraction, primrose_merged1vmega1$i.fraction)  
corprimrose_merged1vmega2            <- cor(primrose_merged1vmega2$fraction, primrose_merged1vmega2$i.fraction)  
corprimrose_merged1vEmseq            <- cor(primrose_merged1vEmseq$fraction, primrose_merged1vEmseq$i.fraction)  
#primrose_merged2
corprimrose_merged2vwgbs1            <- cor(primrose_merged2vwgbs1$fraction, primrose_merged2vwgbs1$i.fraction)  
corprimrose_merged2vwgbs2            <- cor(primrose_merged2vwgbs2$fraction, primrose_merged2vwgbs2$i.fraction)  
corprimrose_merged2vwgbs3            <- cor(primrose_merged2vwgbs3$fraction, primrose_merged2vwgbs3$i.fraction)  
corprimrose_merged2vmega1            <- cor(primrose_merged2vmega1$fraction, primrose_merged2vmega1$i.fraction)  
corprimrose_merged2vmega2            <- cor(primrose_merged2vmega2$fraction, primrose_merged2vmega2$i.fraction)  
corprimrose_merged2vEmseq            <- cor(primrose_merged2vEmseq$fraction, primrose_merged2vEmseq$i.fraction)  



```



### Compare WGBS pooled with Emseq
```{r}
colwgbs1    <- c(1, corwgbs1vwgbs2, corwgbs1vwgbs3, corwgbs1vEmseq, corwgbs1vmega1, corwgbs1vmega2, corprimrose_merged1vwgbs1, corprimrose_merged2vwgbs1)

colwgbs2    <- c(corwgbs1vwgbs2,  1, corwgbs2vwgbs3,   corwgbs2vEmseq,  corwgbs2vmega1,   corwgbs2vmega2, corprimrose_merged1vwgbs2, corprimrose_merged2vwgbs2)

colwgbs3    <- c(corwgbs1vwgbs3,  corwgbs2vwgbs3,  1, corwgbs3vEmseq,  corwgbs3vmega1,  corwgbs3vmega2, corprimrose_merged1vwgbs3, corprimrose_merged2vwgbs3)

colemseq    <- c(corwgbs1vEmseq,  corwgbs2vEmseq,  corwgbs3vEmseq, 1, cormega1vEMseqpull, cormega2vEMseqpull, corprimrose_merged1vEmseq, corprimrose_merged2vEmseq)

colmega1    <- c(corwgbs1vmega1, corwgbs2vmega1,  corwgbs3vmega1, cormega1vEMseqpull, 1, cormega1vmega2, corprimrose_merged1vmega1, corprimrose_merged2vmega1 )

colmega2    <- c(corwgbs1vmega2,  corwgbs2vmega2,  corwgbs3vmega2, cormega2vEMseqpull,  cormega1vmega2,  1, corprimrose_merged1vmega2, corprimrose_merged2vmega2 )

colpacbio1  <- c(corprimrose_merged1vwgbs1, corprimrose_merged1vwgbs2, corprimrose_merged1vwgbs3, corprimrose_merged1vEmseq, corprimrose_merged1vmega1, corprimrose_merged1vmega2, 1, corprimrose_merged1vprimrose_merged2)

colpacbio2  <- c(corprimrose_merged2vwgbs1, corprimrose_merged2vwgbs2, corprimrose_merged2vwgbs3, corprimrose_merged2vEmseq, corprimrose_merged2vmega1, corprimrose_merged2vmega2,corprimrose_merged1vprimrose_merged2,  1)


correlation_matrix <- data.frame(wgbs1 = colwgbs1, wgbs2 = colwgbs2,wgbs3 = colwgbs3, Emseq = colemseq, ont1 = colmega1, ont2 = colmega2, hifi1 = colpacbio1, hifi2 = colpacbio2)
rownames(correlation_matrix) <- c("wgbs1", "wgbs2","wgbs3", "Emseq", "ont1", "ont2", "hifi1", "hifi2")

fwrite(x = round(correlation_matrix, 2), file = "Correlation_matrix_reproducibility_datapaper.5Xallscafoold.last.tsv", sep = "\t")

get_upper_tri <- function(cormat){
  cormat[lower.tri(cormat)]<- NA
  return(cormat)
}

melted_mat <- reshape2:::melt(as.matrix(round(correlation_matrix,2)))

ggplot(data = melted_mat, aes(x=Var1, y=Var2, fill=value)) +
  geom_tile(color = "white")+
  #scale_fill_gradient2(low = "azure4", high = "darkgreen", limit = c(min(melted_mat$value),1), midpoint = median(melted_mat$value))+
  scale_fill_gradient(low = "azure2", high = "chartreuse4") +
  geom_text(aes(label = value), size = 5) +
  theme(axis.text = element_text(size = 10), axis.title=element_blank())


```
